<?php

/* originally from Icinga Web 2 X.509 Module | (c) 2018 Icinga GmbH | GPLv2 */
/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\Oidc\Controllers;

use Exception;
use Icinga\Application\Config;
use Icinga\Application\Logger;
use Icinga\Data\ResourceFactory;
use Icinga\Exception\ConfigurationError;
use Icinga\Exception\NotFoundError;
use Icinga\Forms\Config\UserBackendConfigForm;
use Icinga\Forms\ConfirmRemovalForm;
use Icinga\Module\Oidc\BackendTable;
use Icinga\Module\Oidc\Common\Database;
use Icinga\Module\Oidc\CompatTabs;
use Icinga\Module\Oidc\Forms\BackendConfigForm;
use Icinga\Web\Notification;
use ipl\Html\Html;
use ipl\Web\Compat\CompatController;
use ipl\Web\Widget\ButtonLink;
use SQLite3;

class ConfigController extends CompatController
{
    public function init()
    {
        $this->assertPermission('config/modules');

        parent::init();
    }

    public function backendAction()
    {
        $form = (new BackendConfigForm())
            ->setIniConfig(Config::module('oidc'));

        $form->handleRequest();

        $this->view->tabs = $this->Module()->getConfigTabs()->activate('backend');
        $this->view->form = $form;
    }

    /**
     * Action for listing user and group backends
     */
    public function importBackendAction()
    {
        $this->assertPermission('config/oidc');
        $tabs = (new CompatTabs())->setTabs($this->Module()->getConfigTabs());
        $this->controls->setTabs($tabs->activate('importbackend'));

        $this->addControl(
            (new ButtonLink($this->translate('New'), \ipl\Web\Url::fromPath('oidc/config/createuserbackend'), 'plus'))->openInModal());

        $data =[];
        foreach ($this->Config('userbackends')->keys() as $id) {
            $item = ['name'=>$id,'id'=>$id];
            $data[]= (object) $item;
        }

        //$this->view->content=(new BackendTable())->setData($data);
        $this->addContent((new BackendTable())->setData($data));


    }


    /**
     * Create a new user backend
     */
    public function createuserbackendAction()
    {
        $this->assertPermission('config/oidc');
        $form = new UserBackendConfigForm();

        $form
            ->setRedirectUrl('oidc/config/import-backend')
            ->addDescription($this->translate(
                'Create a new backend for oidc imports. Please only choose'
                . ' LDAP or Active Directory.'
            ))
            ->setIniConfig($this->Config('userbackends'));

        try {
            $form->setResourceConfig(ResourceFactory::getResourceConfigs());
        } catch (ConfigurationError $e) {
            if ($this->hasPermission('config/resources')) {
                Notification::error($e->getMessage());

                $this->redirectNow('oidc/config/import-backend');
            }

            throw $e; // No permission for resource configuration, show the error
        }

        $form->setOnSuccess(function (UserBackendConfigForm $form) {
            try {
                $form->add($form::transformEmptyValuesToNull($form->getValues()));
            } catch (Exception $e) {
                $form->error($e->getMessage());
                return false;
            }

            if ($form->save()) {
                Notification::success(t('User backend successfully created'));
                $this->closeModalAndRefreshRelatedView('oidc/config/import-backend');
                return true;
            }

            return false;
        });

        /**
        // does not work at the moment
        $form->create();
        $options = $form->getElement('type')->getAttribs()['options'];
        $filtered = array_intersect_key(
            $options,
            array_flip(['ldap', 'msldap'])
        );
        $form->getElement('type')->setAttrib('options', $filtered);
        **/
        $form->handleRequest();

        $this->view->title = $this->translate('Import Backend');
        $this->renderForm($form, $this->translate('New User Backend'));


    }
    /**
     * Edit a user backend
     */
    public function edituserbackendAction()
    {
        $this->assertPermission('config/oidc');
        $backendName = $this->params->getRequired('backend');

        $form = new UserBackendConfigForm();
        $form->setRedirectUrl('oidc/config/import-backend');
        $form->setIniConfig($this->Config('userbackends'));
        $form->addDescription($this->translate(
        'Update a backend for oidc imports. Please only choose'
        . ' LDAP or Active Directory.'
        ));
        $form->setOnSuccess(function (UserBackendConfigForm $form) use ($backendName) {
            try {
                $form->edit($backendName, $form::transformEmptyValuesToNull($form->getValues()));
            } catch (Exception $e) {
                $form->error($e->getMessage());
                return false;
            }

            if ($form->save()) {
                Notification::success(sprintf(t('User backend "%s" successfully updated'), $backendName));
                $this->closeModalAndRefreshRelatedView('oidc/config/import-backend');

                return true;
            }

            return false;
        });

        try {
            $form->load($backendName);
            $form->setResourceConfig(ResourceFactory::getResourceConfigs());
            /**
            // does not work at the moment
            $form->create();
            $options = $form->getElement('type')->getAttribs()['options'];
            $filtered = array_intersect_key(
            $options,
            array_flip(['ldap', 'msldap'])
            );
            $form->getElement('type')->setAttrib('options', $filtered);
             **/
            $form->handleRequest();
        } catch (NotFoundError $_) {
            $this->httpNotFound(sprintf($this->translate('User backend "%s" not found'), $backendName));
        }

        $this->view->title = $this->translate('Import Backend');
        $this->renderForm($form, $this->translate('Update User Backend'));
    }

    /**
     * Display a confirmation form to remove the backend identified by the 'backend' parameter
     */
    public function removeuserbackendAction()
    {
        $this->assertPermission('config/oidc');
        $backendName = $this->params->getRequired('backend');

        $backendForm = new UserBackendConfigForm();
        $backendForm->setIniConfig($this->Config('userbackends'));
        $form = new ConfirmRemovalForm();
        $form->setRedirectUrl('oidc/config/import-backend');
        $form->setOnSuccess(function (ConfirmRemovalForm $form) use ($backendName, $backendForm) {
            try {
                $backendForm->delete($backendName);
            } catch (Exception $e) {
                $form->error($e->getMessage());
                return false;
            }

            if ($backendForm->save()) {
                Notification::success(sprintf(t('User backend "%s" successfully removed'), $backendName));
                $this->closeModalAndRefreshRelatedView('oidc/config/import-backend');

                return true;
            }

            return false;
        });
        $form->handleRequest();

        $this->view->title = $this->translate('Authentication');
        $this->renderForm($form, $this->translate('Remove User Backend'));
    }

}
