<?php

/* originally from Icinga Web 2 X.509 Module | (c) 2018 Icinga GmbH | GPLv2 */
/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\Oidc\Controllers;


use Icinga\Application\Config;
use Icinga\Application\Hook\AuditHook;
use Icinga\Application\Hook\AuthenticationHook;
use Icinga\Authentication\Auth;
use Icinga\Exception\Http\HttpException;
use Icinga\Exception\Http\HttpMethodNotAllowedException;
use Icinga\Exception\NotFoundError;
use Icinga\Module\Oidc\Forms\ImpersonateForm;
use Icinga\Module\Oidc\Model\Provider;
use Icinga\Module\Oidc\UserRestrictor;
use Icinga\Module\Oidc\Controller;
use Icinga\Module\Oidc\Forms\UserForm;
use Icinga\Module\Oidc\Model\User;
use Icinga\Web\Notification;
use ipl\Html\Form;
use Icinga\Module\Oidc\Common\Database;
use ipl\Stdlib\Filter;
use ipl\Web\Url;


class UserController extends Controller
{
    /** @var User The User object */
    protected $user;
    protected $db;

    public function init()
    {
        if(!$this->Auth()->hasPermission("oidc/user/modify")){
            throw new HttpException(401,"Not allowed!");
        }
        $this->db=Database::get();

    }
    public function importAction()
    {

        $this->setTitle($this->translate('New User'));
        $name = $this->params->getRequired("name");
        $backend = $this->params->getRequired("backend");
        $values = ['name'=>$name, 'active'=>'y'];

        $form = (UserForm::fromId(null))->setDb($this->db)
            ->setAction((string) Url::fromRequest())->setRenderCreateAndShowButton(false)
            ->populate($values)
            ->on(UserForm::ON_SUCCESS, function (UserForm $form) use ($backend, $name) {

                    Notification::success($this->translate('Updated User successfully'));
                    $this->redirectNow(Url::fromPath('oidc/import/show',['user'=>$name,'backend'=>$backend]));


            })
            ->handleRequest($this->getServerRequest());

        $this->addContent($form);

    }

    public function newAction()
    {

        $this->setTitle($this->translate('New User'));

        $values = [];

        $form = (UserForm::fromId(null))->setDb($this->db)
            ->setAction((string) Url::fromRequest())->setRenderCreateAndShowButton(false)
            ->populate($values)
            ->on(UserForm::ON_SUCCESS, function (UserForm $form) {
                $pressedButton = $form->getPressedSubmitElement();
                if ($pressedButton && $pressedButton->getName() === 'remove') {
                    Notification::success($this->translate('Removed User successfully'));


                    $this->closeModalAndRefreshRemainingViews(
                        Url::fromPath('oidc/users')
                    );
                } else {
                    Notification::success($this->translate('Updated User successfully'));

                    $this->closeModalAndRefreshRemainingViews(
                        Url::fromPath('oidc/users')
                    );
                }
            })
            ->handleRequest($this->getServerRequest());

        $this->addContent($form);

    }

    public function editAction()
    {

        $this->setTitle($this->translate('Edit User'));

        $id = $this->params->getRequired('id');

        $query = User::on($this->db)->with([

        ]);
        $query->filter(Filter::equal('id', $id));

        $restrictor = new UserRestrictor();
        $restrictor->applyRestrictions($query);

        $user = $query->first();
        if ($user === null) {
            throw new NotFoundError(t('Entry not found'));
        }

        $this->user = $user;




        $values = $this->user->getValues();




        $form = (UserForm::fromId($id))->setDb($this->db)
            ->setAction((string) Url::fromRequest())->setRenderCreateAndShowButton(false)
            ->populate($values)
            ->on(UserForm::ON_SUCCESS, function (UserForm $form) {
                $pressedButton = $form->getPressedSubmitElement();
                if ($pressedButton && $pressedButton->getName() === 'remove') {
                    Notification::success($this->translate('Removed User successfully'));


                    $this->closeModalAndRefreshRemainingViews(
                        Url::fromPath('oidc/users')
                    );
                } else {
                    Notification::success($this->translate('Updated User successfully'));

                    $this->closeModalAndRefreshRemainingViews(
                        Url::fromPath('oidc/users')
                    );
                }
            })
            ->handleRequest($this->getServerRequest());

        $this->addContent($form);

    }

    protected function redirectForm(Form $form, $url)
    {
        if (
            $form->hasBeenSubmitted()
            && ((isset($form->valid) && $form->valid === true)
                || $form->isValid())
        ) {
            $this->redirectNow($url);
        }
    }

    public function impersonateAction()
    {
        $this->assertPermission('oidc/user/impersonate');
        $this->setTitle($this->translate('Impersonate'));


        $query = User::on(Database::get())
            ->filter(Filter::equal('name', $this->params->getRequired('username')));

        $restrictor = new UserRestrictor();
        $restrictor->applyRestrictions($query);

        $oidcUser = $query->first();
        if ($oidcUser === null) {
            throw new NotFoundError(t('Entry not found'));
        }
        $provider = Provider::on(Database::get())->filter(Filter::equal('id', $oidcUser->provider_id))->first();



        $form = (ImpersonateForm::fromUser($oidcUser))
            ->setAction((string) Url::fromRequest())->setRedirectUrl(Url::fromPath('dashboard'))
            ->on(ImpersonateForm::ON_SUCCESS, function (ImpersonateForm $form) use ($oidcUser, $provider) {
                $pressedButton = $form->getPressedSubmitElement();
                if ($pressedButton) {
                    Notification::success($this->translate('Updated User successfully'));
                    $auth = Auth::getInstance();
                    $oldUsername = $auth->getUser()->getUserName();
                    $backendType =null;
                    if (isset($oidcUser->mapped_local_user) && $oidcUser->mapped_local_user !== "" && $oidcUser->mapped_local_user !== null) {

                        $user = new \Icinga\User($oidcUser->mapped_local_user);

                        if (isset($oidcUser->mapped_backend) && $oidcUser->mapped_backend !== "" && $oidcUser->mapped_backend !== null) {
                            $backendName = $oidcUser->mapped_backend;
                            $backendType = Config::app('authentication')->getSection($backendName)->get('backend');

                        } else {
                            $backendName = null;
                            $backendType = null;
                        }


                    } else {
                        $backendName = $provider->getUserBackendName();
                        $backendType = 'oidc';
                        $user = new \Icinga\User($oidcUser->name);
                    }

                    AuditHook::logActivity('login-impersonate',sprintf("User logged in as %s", $user->getUsername()), null, $oldUsername);

                    $user->setAdditional('backend_name', $backendName);
                    $user->setAdditional('backend_type', $backendType);
                    $user->setAdditional('provider_id', $provider->id);

                    $auth->setAuthenticated($user);


                    // Call provided AuthenticationHook(s) after successful login
                    AuthenticationHook::triggerLogin($user);
                    $this->getResponse()->setHeader('X-Icinga-Rerender-Layout', 'yes', true);
                    $this->getResponse()->setHeader('X-Icinga-Reload-Css', 'now', true);
                    $this->getResponse()->setHeader('X-Icinga-Redirect',  rawurlencode(Url::fromPath('dashboard')->getAbsoluteUrl()), true);
                }
            })
            ->handleRequest($this->getServerRequest());

        $this->addContent($form);

    }

}
