
# introduce table group membership by id not name
ALTER TABLE `tbl_group_membership`
    ADD COLUMN `user_id` INT(10) UNSIGNED NULL AFTER `provider_id`;

# update the id by name
UPDATE tbl_group_membership gm
    JOIN tbl_user u
ON u.name = gm.username
    AND u.provider_id = gm.provider_id
    SET gm.user_id = u.id;

# update make the id not null
ALTER TABLE `tbl_group_membership`
    MODIFY COLUMN `user_id` INT(10) UNSIGNED NOT NULL;

# remove all forgain keys in table group membership because they where autogenerated

SET @sql = (
    SELECT CONCAT(
        'ALTER TABLE `tbl_group_membership` ',
        GROUP_CONCAT(
            CONCAT('DROP FOREIGN KEY `', CONSTRAINT_NAME, '`')
            SEPARATOR ', '
        )
    )
    FROM information_schema.KEY_COLUMN_USAGE
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'tbl_group_membership'
      AND REFERENCED_TABLE_NAME IS NOT NULL
);

PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;


# generate the forgain keys with a preset name and the new fk pointing to user->is
ALTER TABLE `tbl_group_membership`
    ADD CONSTRAINT `fk_group_membership_provider`
        FOREIGN KEY (`provider_id`)
            REFERENCES `tbl_provider` (`id`)
            ON DELETE CASCADE,
    ADD CONSTRAINT `fk_group_membership_group`
        FOREIGN KEY (`group_id`)
        REFERENCES `tbl_group` (`id`)
        ON DELETE CASCADE,
    ADD CONSTRAINT `fk_group_membership_user`
        FOREIGN KEY (`user_id`)
        REFERENCES `tbl_user` (`id`)
        ON DELETE CASCADE;

# making the username unique by provider
ALTER TABLE tbl_user
DROP INDEX uq_oidc_user_name,
    ADD UNIQUE INDEX uq_oidc_user_provider_name (provider_id, `name`) USING BTREE;

# making the groupname unique by provider

ALTER TABLE tbl_group
DROP INDEX uq_oidc_group_name,
    ADD UNIQUE INDEX uq_oidc_group_name (provider_id, `name`) USING BTREE;

# introduce a prefix for username and groupname
ALTER TABLE `tbl_provider`
    ADD COLUMN `username_prefix` VARCHAR(255)  DEFAULT '' AFTER `custom_username`,
    ADD COLUMN `groupname_prefix` VARCHAR(255) DEFAULT '' AFTER `username_prefix`;


INSERT INTO tbl_schema (version, timestamp, success, reason)
VALUES ('0.6.1', UNIX_TIMESTAMP() * 1000, 'y', NULL);
