<?php

/* originally from Icinga Web 2 Reporting Module | (c) 2019 Icinga GmbH | GPLv2 */
/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\Oidc\Forms;

use Icinga\Application\Hook\AuditHook;
use Icinga\Application\Hook\AuthenticationHook;
use Icinga\Authentication\Auth;
use Icinga\User;
use ipl\Web\Compat\CompatForm;

class ImpersonateForm extends CompatForm
{

    /* @var $oidcUser \Icinga\Module\Oidc\Model\User */
    protected $oidcUser;





    /**
     * Set whether the create and show submit button should be rendered
     *
     * @param bool $renderCreateAndShowButton
     *
     * @return \Icinga\Module\Oidc\Forms\UserForm
     */
    public function setRenderCreateAndShowButton(bool $renderCreateAndShowButton): self
    {
        $this->renderCreateAndShowButton = $renderCreateAndShowButton;

        return $this;
    }

    /**
     * Create a new form instance with the given user id
     *
     * @param $id
     *
     * @return \Icinga\Module\Oidc\Forms\UserForm
     */
    public static function fromUser($oidcUser): self
    {
        $form = new static();
        $form->oidcUser = $oidcUser;

        return $form;
    }

    public function hasBeenSubmitted(): bool
    {
        return $this->hasBeenSent() && $this->getPopulatedValue('submit');
    }


    protected function assemble()
    {

        $this->addElement(
            'text',
            'username',
            array(
                'label'    => $this->translate('Username'),
                'disabled'    => 'disabled',
                'autocapitalize'    => 'off',
                'autocomplete'      => 'username',
                'class'             => false === isset($formData['username']) ? 'autofocus' : '',
                'value'=> $this->oidcUser->name,
                'readonly' => 'readonly',
            )
        );

        $this->addElement('submit', 'submit', [
            'label' => $this->translate('Impersonate')
        ]);

    }


    /**
     * {@inheritdoc}
     */
    public function onSuccess()
    {

        return true;

    }

}

